import GreenSofa from "./assets/greenSofa.jpg";

const products = [
  {
    id: 1,
    title: "Scandinavian Sofa",
    image: GreenSofa,
    rating: {
      rate: 4,
      count: 120,
    },
    description: "A comfortable green sofa chair, perfect for any living room.",
    category: "Chairs",
    colors: ["#FFFF00", "#FFF68F", "#000000", "#CCCCCC"],
    year: 2023,
    price: "25.00 - 30.00",
    features: [
      "Elegant Design: Featuring clean lines and a minimalist aesthetic, this sofa effortlessly complements any decor style.",
      "Premium Materials: Upholstered in high-quality, breathable fabric with a sturdy wooden frame for long-lasting durability.",
      "Ultimate Comfort: Generously padded cushions with a plush, supportive feel ensure you can relax in luxury.",
      "Versatile Color Options: Available in chic neutral tones that blend seamlessly with your existing furniture.",
    ],
    images: [GreenSofa, GreenSofa, GreenSofa, GreenSofa],
  },
  {
    id: 2,
    title: "Scandinavian Sofa",
    image: GreenSofa,
    rating: {
      rate: 4,
      count: 120,
    },
    description: "A comfortable green sofa chair, perfect for any living room.",
    category: "sofa",
    colors: ["#FFFF00", "#FFF68F", "#000000", "#CCCCCC"],
    year: 2023,
    price: "25.00 - 30.00",
    features: [
      "Elegant Design: Featuring clean lines and a minimalist aesthetic, this sofa effortlessly complements any decor style.",
      "Premium Materials: Upholstered in high-quality, breathable fabric with a sturdy wooden frame for long-lasting durability.",
      "Ultimate Comfort: Generously padded cushions with a plush, supportive feel ensure you can relax in luxury.",
      "Versatile Color Options: Available in chic neutral tones that blend seamlessly with your existing furniture.",
    ],
    images: [GreenSofa, GreenSofa, GreenSofa, GreenSofa],
  },
  {
    id: 4,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 5,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 6,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 7,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 8,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 9,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 10,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 11,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 12,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 13,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 14,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 15,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 16,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 17,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 18,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 19,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 20,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 21,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 22,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 23,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 24,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 25,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 26,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 27,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 28,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 29,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 30,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 31,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 32,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 33,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 34,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 35,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 36,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 37,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 38,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 39,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 40,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 41,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 42,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 43,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 44,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 45,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
  {
    id: 46,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    description: "A stylish Scandinavian sofa with a minimalist design.",
    category: "Sofa",
  },

  {
    id: 47,
    title: "Green Sofa Chair",
    image: GreenSofa,
    price: "350.00",
    rating: {
      rate: 4,
      count: 50,
    },
    category: "sofa",
  },
];

export default products;
